export enum ACTIVITY_EVENT_TYPES {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
}

export enum ACTIVITY_OBJECT_TYPES {
  COMMUNITY = 'COMMUNITY',
  GROUP = 'GROUP',
  MEMBER = 'MEMBER',
  GROUP_SET = 'GROUP_SET',
  GENERAL_SCHEME = 'GENERAL_SCHEME',
  GROUP_SCHEME = 'GROUP_SCHEME',
  GROUP_BADGE = 'GROUP_BADGE',

  ARTICLE = 'ARTICLE',
  POST = 'POST',
  SERIES = 'SERIES',
}

export enum BADGE_TYPE {
  GROUP = 'GROUP',
  ACHIEVEMENT = 'ACHIEVEMENT',
}

export enum SCHEME_SCOPE {
  SYSTEM = 'SYSTEM',
  COMMUNITY = 'COMMUNITY',
  GROUP = 'GROUP',
}
